// export {default as Main} from './Main'
export {default as Actor} from './Actor'
export {default as Home} from './Home'
export {default as User} from './User'
export {default as Rating} from './Rating'
export {default as Movie} from './Movie'