export {default as MovieDetail} from './MovieDetail'
export {default as MovieRegister} from './MovieRegister'
export {default as MovieList} from './MovieList'
export {default as MovieModify} from './MovieModify'
export {default as MovieRemove} from './MovieRemove'
